---
- name: Check site's availability
  hosts: nodes
  gather_facts: false
  tasks:
    - name: healthcheck-python
      healthcheck_py:
        addr: "portal.plk32.local"
        tls: false
    - name: healthcheck-bash
      healthcheck_sh:
        addr: "portal.plk32.local"
        tls: false