- name: test module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Example module
      example_sh:
        string1: value1
      register: bash_result

    - name: print result
      debug:
        msg: "{{ bash_result }}"

    - name: Example module
      example_py:
        string1: value1
      register: py_result

    - name: print result
      debug:
        msg: "{{ py_result }}"
    