---
- name: free
  hosts: nodes
  connection: local
  strategy: free
  gather_facts: false
  tasks:
    - name: first task
      command: sleep "{{ sleep_seconds }}"
      changed_when: false

    - name: second task
      command: sleep "{{ sleep_seconds }}"
      changed_when: false

    - name: third task
      command: sleep "{{ sleep_seconds }}"
      changed_when: false
