---
- name: free
  hosts: nodes
  connection: local
  strategy: free
  gather_facts: false
  tasks:
    - name: first task
      shell: sleep "{{ sleep_seconds }}"
      
    - name: second task
      shell: sleep "{{ sleep_seconds }}"

    - name: third task
      shell: sleep "{{ sleep_seconds }}"
